### PR TITLE
48 create faker factory bot test data

### PR DESCRIPTION
**Pull request by vsanantone**
Factorybot/Faker Set up

### CODE REVIEW

**Review by Dylan-Perry — APPROVED** [review]
I merged the conflicts in the Gemfile and rails_helper, was super innocuous stuff related to the platform versions in the former and a missing end in the latter. All good now

**Comment by s2an** [comment]
Looks good to me. Thanks for giving us an overview of how it works Victor!

**Comment by Dylan-Perry** [comment]
Note: this PR contains an untested implementation of Faker and Factory Bot. Pushing up because testing requires the models available in PR #6 and #7

**Review by megroth2 — APPROVED** [review]

**Review by s2an — APPROVED** [review]
Looks great. Thanks for the overview of how it works, Victor!

**Pull request merged**
